### ISSUE TITLE
Not being able to close voice connections (using discordgo)?

### ISSUE THREAD

**Issue by zekroTJA** [foxbot/gavalink#3]
To create a player, you need to pass the data of a `VoiceServerUpdate` event. But if this handler is registered, you can only join a voice channel with [`VoiceJoinManual`](https://godoc.org/github.com/bwmarrin/discordgo#Session.ChannelVoiceJoinManual). But this method does not return the actual [`VoiceConnection`](https://godoc.org/github.com/bwmarrin/discordgo#VoiceConnection), which needs to be used to manually disconnect from a voice channel.   

But using [`ChannelVoiceJoin`](https://godoc.org/github.com/bwmarrin/discordgo#Session.ChannelVoiceJoin) leads to an issue that no sound is played. For some reason, the execution of the `VoiceServerUpdate` is successful and also creates a player for the guild. Also, the `Play` method of the player does not throw an error. Even the lavalink console confirms that the sound should have been played.

I do not really know it this is a problem of gavaplayer, discordgo or even lavalink, but maybe you have a quick idea to solve this problem.

**Comment by tyhi** [comment]
I was in the same situation, based on lavalink docs you're suppose to kill the connection yourself. In order to do that you must pass null as the channel id in that guild (https://discordapp.com/developers/docs/topics/gateway#update-voice-state). You can use ChannelVoiceJoinManual() to pass that but you have to use a nil pointer and not a empty string. Passing a empty string will cause the entire bot session to disconnect. I created a PR to catch if the channel is empty and convert it to nil but didn't seem to get traction. 

https://github.com/bwmarrin/discordgo/pull/609

**Comment by zekroTJA** [comment]
Thank you very much, this solution has solved my problem. I've forked bwmarrin/discordgo and [passed a nil pointer instead of an empty string](https://github.com/zekroTJA/discordgo/blob/master/wsapi.go#L650) and it works out fine.

Before, I had another solution for this problem *(just in case someone is interested)*:

You can *kick* yourself *(or als other members)* out of voice channels by creating a new voice channel, moving yourself into it and then deleting the voice channel.

```go
ch, err := p.session.GuildChannelCreate(guildID, "tmp", discordgo.ChannelTypeGuildVoice)
if err != nil {
	return err
}

if err = p.session.ChannelVoiceJoinManual(guildID, ch.ID, false, true); err != nil {
	return err
}

_, err = p.session.ChannelDelete(ch.ID)
return err
```

It's a bit dirty and you will need the permissions to create channels and move members, but it also kind of wokrs.
